print("True or False is", True or False) # OR (or)
print("True or true is", True or False)
print("False or False is", False or False)
print("false or true is",  True or False)

# AND (and)
print("\nTrue and False is", True and  False)
print("True and True is", True and  False) 
print("False and False is", False and False)
print("False and True is", True and False)
# NOT (!=)
print(not(True))
print(not(False))

